@hostname = localhost
@port = 8000
@host = {{hostname}}:{{port}}
@contentType = application/json

# Test API
###
GET http://{{host}}/api/test HTTP/1.1

# Login user with valid credentials
####
# @prompt username
# @prompt password
GET http://{{host}}/ HTTP/1.1

###
# Register user with valid credentials
POST http://{{host}}/register HTTP/1.1
{
    "name": "test",
    "password": "test",
    "email": "testemail@gmail.com",
    "dni": 1231234
}

###
# Login user with invalid credentials

###
# Register user with invalid credentials

###
# Fetch events

###
# Fetch event by id

###
# Fetch event by id with invalid id

###
# Order ticket

###
# Order ticket with invalid event id

###
# Show all my tickets with valid credentials

###
# Show all my tickets with invalid credentials

###
# Show a ticket by id with valid credentials


